# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  default:
    - step: &testStep
        name: Test
        caches:
          - node
        script:
          - sed "s/\${NPM_TOKEN}/${NPM_TOKEN}/g" npmrc_config > ~/.npmrc
          - npm install
  branches:
    master:
      - step: *testStep
      - step:
          name: Deploy
          script:
            - echo "${SSH_PUBLIC_KEY}" >> ~/.ssh/authorized_keys
            - git config --global push.default simple
            - git config --global user.email "${EMAIL}"
            - git config --global user.name "${NAME}"
            - sed "s/\${NPM_TOKEN}/${NPM_TOKEN}/g" npmrc_config > ~/.npmrc
            - echo "${NPM_TOKEN}" | wc -c
            - npm install
            - npm version minor -m "%s [skip ci]"
            - npm publish
            - git push && git push --tags